name: cost_calculator
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  screenshot: ^3.0.0  # Para capturar a tela como imagem
  share_plus: ^10.1.0
  permission_handler: ^11.3.1
  image_picker: ^1.0.7
  supabase_flutter: ^2.6.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0
  url_launcher_android: ^6.2.4
  url_launcher_ios: ^6.2.4
  url_launcher_web: ^2.2.9
  url_launcher_linux: ^3.1.0
  url_launcher_macos: ^3.1.0
  url_launcher_windows: ^3.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo1.png
